face/urls.py
from django.contrib import admin
from django.urls import path, include
from page import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('page/', include('page.urls')),
    path('', views.index )
]

page/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'page'

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('who/', views.who, name='who'),
    path('merge/', views.merge, name='merge'),
    path('mixed/<str:name>', views.mixed, name='mixed'),
    path('mixed_all/<str:name1>/<str:name2>/<str:name3>', views.mixed_all, name='mixed_all'),
    path('photo_list',views.photo_list,name='photo_list'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

page/models.py
from django.db import models

# Create your models here.

page/views.py
from django.shortcuts import render
import cv2, os,json
import numpy as np
import face_recognition as fr
import matplotlib.pyplot as plt
from page.module.img_cropped import img_crop, use_crop
from page.module.opencv import use_opencv
from page.module.base64 import use_base64
import glob

def index(request):
    return render(request, 'index.html')

def who(request):

    if request.method == 'POST':
        sex = request.POST.get('sex')
        me = fr.load_image_file(request.FILES['profile_pt'].file)

        me = use_crop(me)

        b,g,r = cv2.split(me)
        me = cv2.merge([r,g,b])
        #me = use_base64(me)

        # session에 저장하기 위해 list로 변경
        list_me = me.tolist()
        # me로 저장
        request.session['me'] = list_me

        # 얼굴 찾기
        me_face_locations = fr.face_locations(me, model='cnn')
        for (top, right, bottom, left) in me_face_locations:
            me_face = me[top:bottom, left:right]
        enc_me = fr.face_encodings(me_face)

        me = use_base64(me)

        who_top = []
        # 전체 배우 데이터
        file_path = "actor.json"
        with open(file_path, "r") as json_file:
            json_data = json.load(json_file)
            if sex == 'man':
                for i in range(len(json_data['man'])):
                    image = json_data['man'][i]['image']

                    enc = json_data['man'][i]['enc_actor']
                    
                    img_src = use_base64(image)
                    
                    who_top.append(
                        {'name': json_data['man'][i]['name'],
                        'how': (fr.face_distance(np.array(enc), enc_me)).tolist(),
                        'image': img_src,
                        })

            else:
                for i in range(len(json_data['woman'])):
                    image = json_data['woman'][i]['image']
                    enc = json_data['woman'][i]['enc_actor']
                    
                    # 배우 이미지 가져오기
                    img_src = use_base64(image)

                    who_top.append(
                        {'name': json_data['woman'][i]['name'],
                        'how': (fr.face_distance(np.array(enc), enc_me)).tolist(),
                        'image': img_src,
                        })

            top3 = sorted(who_top, key=(lambda x: x['how']))

            return render(request, 'who.html', 
                            {
                            # 'me':me,
                            'img_src': [top3[0], top3[1], top3[2]]
                            }
                            )
    else:
        return render(request, 'index.html')


def merge(request):
    return render(request, 'merge.html')

def mixed(request, name):
    arr = request.session['me']
    me = np.array(arr, dtype = np.uint8)

    me_re = use_crop(me)
    img_3 = use_opencv(me, 'page/image/'+name+'.jpg',0.3)
    img_5 = use_opencv(me, 'page/image/'+name+'.jpg',0.5)
    img_7 = use_opencv(me, 'page/image/'+name+'.jpg',0.7)
    me_no = img_crop('page/image/'+name+'.jpg')

    # 색상을 반전시켜준다
    b,g,r = cv2.split(me_re)
    me_re = cv2.merge([r,g,b])
    me_re = use_base64(me_re)

    b,g,r = cv2.split(img_3)
    img_3 = cv2.merge([r,g,b])
    img_3 = use_base64(img_3)

    b,g,r = cv2.split(img_5)
    img_5 = cv2.merge([r,g,b])
    img_5 = use_base64(img_5)

    b,g,r = cv2.split(img_7)
    img_7 = cv2.merge([r,g,b])
    img_7 = use_base64(img_7)

    b,g,r = cv2.split(me_no)
    me_no = cv2.merge([r,g,b])
    me_no = use_base64(me_no)

    return render(request, 'mix.html',{'me_re':me_re,'me_3':img_3,'me_5':img_5,'me_7':img_7,'me_no':me_no})

    #cv2.imshow("Morphed Face", me)
    #cv2.waitKey(0)

def mixed_all(request, name1, name2, name3):
    arr = request.session['me']
    me = np.array(arr, dtype = np.uint8)
    
    me_re = use_crop(me)
    img_1 = use_opencv(me, 'page/image/'+name1+'.jpg',0.5)
    img_2 = use_opencv(me, 'page/image/'+name2+'.jpg',0.5)
    img_3 = use_opencv(me, 'page/image/'+name3+'.jpg',0.5)
    me_no_1 = img_crop('page/image/'+name1+'.jpg')
    me_no_2 = img_crop('page/image/'+name2+'.jpg')
    me_no_3 = img_crop('page/image/'+name3+'.jpg')

    b,g,r = cv2.split(me_re)
    me_re = cv2.merge([r,g,b])
    me_re = use_base64(me_re)

    b,g,r = cv2.split(img_1)
    img_1 = cv2.merge([r,g,b])
    img_1 = use_base64(img_1)

    b,g,r = cv2.split(img_2)
    img_2 = cv2.merge([r,g,b])
    img_2 = use_base64(img_2)

    b,g,r = cv2.split(img_3)
    img_3 = cv2.merge([r,g,b])
    img_3 = use_base64(img_3)

    b,g,r = cv2.split(me_no_1)
    me_no_1 = cv2.merge([r,g,b])
    me_no_1 = use_base64(me_no_1)

    b,g,r = cv2.split(me_no_2)
    me_no_2 = cv2.merge([r,g,b])
    me_no_2 = use_base64(me_no_2)

    b,g,r = cv2.split(me_no_3)
    me_no_3 = cv2.merge([r,g,b])
    me_no_3 = use_base64(me_no_3)

    return render(request, 'mix_all.html',{'me':me_re,'me_1':img_1,'me_2':img_2,'me_3':img_3,'me_no_1':me_no_1,'me_no_2':me_no_2,'me_no_3':me_no_3})

def photo_list(request):
    images = glob.glob('page/image/*.jpg')

    images_list = []

    for img in images:
        rgb_image = img_crop(img)
        img = img.split(".")[0].split('\\')[-1]
        try:
            b,g,r = cv2.split(rgb_image)
            rgb_image = cv2.merge([r,g,b])
            rgb_image = use_base64(rgb_image)
            images_list.append({'name':img,'img':rgb_image})
        except:
            print('error',img)

    return render(request, 'photo_list.html',{'img_list':images_list})

page/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Face_Mix</title>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/admin/css/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
    <div class="base">
        <div class='navi'>
            <div class ='main_logo'>
                <a href="{% url 'page:index'%}">
                    <img class = 'logo' src="/static/admin/css/turn.png">
                </a>
            </div>
        </div>
    {% block body %}
    {% endblock %}
    </div>
</body>
</html>

page/templates/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<style>
	.upload {
        box-sizing: border-box;
        width: 210px;
        height: 240px;
		background-color: beige ;
		border-radius:30%
    }
	#input_wrapper { 
		border: 1px solid rgb(19, 58, 71);
		border-radius: 15px;
		padding: 5px 20px;
		position: absolute;
		top: 45%;
		left: 50%;
		width: 500px; height: 550px;
		margin-left: -220px;
		margin-top : -170px;
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		background-color: rgba( 176, 176, 176, 0.8 );
	} 
	button{
		width: 85px;
		float: right;
		margin-top: 5%;
	}

	.filebox label {
		display: inline-block;
		padding: .5em .75em;
		color: rgb(65, 62, 62);
		font-size: inherit;
		line-height: normal;
		vertical-align: middle;
		background-color: rgba( 256, 256, 256);
		cursor: pointer;
		border: 1px solid rgba( 0, 0, 0);
		border-radius: .25em;
		-webkit-transition: background-color 0.2s;
		transition: background-color 0.2s;
	}

	.filebox label:hover {
		background-color: rgba( 230, 230, 230);
	}

	.filebox label:active {
		background-color: #abe6ab;
	}

	.filebox input[type="file"] {
		position: absolute;
		width: 1px;
		height: 1px;
		padding: 0;
		margin: -1px;
		overflow: hidden;
		clip: rect(0, 0, 0, 0);
		border: 0;
	}
</style>

<div class = 'index_back_ground'>
<div class='tri'>
</div>
	<div id="input_wrapper" style="text-align: center;">
			<form action="{% url 'page:who' %}" class="form" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<div style="margin-bottom: 10%;">
				<h5>성별체크</h5>
				<div class="form-check-inline">
					<input class="form-check-input" type="radio" name="sex" id="exampleRadios1" value="woman" checked>
					<label class="form-check-label" for="exampleRadios1">
						여자
					</label>
				</div>
				<div class="form-check-inline">
					<input class="form-check-input" type="radio" name="sex" id="exampleRadios2" value="man">
					<label class="form-check-label" for="exampleRadios2">
						남자
					</label>
				</div>
				<div class="filebox">
					<label for="profile_pt">사진을 업로드해 주세요</label>
					<input type="file" name="profile_pt" id="profile_pt" onchange="previewImage(this,'View_area')">
				</div>
			</div>
			<div class="upload">
				<div id='View_area'>
				</div>
			</div>
			<button type="submit" class="btn btn-dark" style="margin-top: 40px">검색</button>
		</form>
	</div>  
</div>


<script> 
function previewImage(targetObj, View_area) {
	var preview = document.getElementById(View_area); //div id
	var ua = window.navigator.userAgent;

  //ie일때(IE8 이하에서만 작동)
	if (ua.indexOf("MSIE") > -1) {
		targetObj.select();
		try {
			var src = document.selection.createRange().text; // get file full path(IE9, IE10에서 사용 불가)
			var ie_preview_error = document.getElementById("ie_preview_error_" + View_area);


			if (ie_preview_error) {
				preview.removeChild(ie_preview_error); //error가 있으면 delete
			}

			var img = document.getElementById(View_area); //이미지가 뿌려질 곳

			//이미지 로딩, sizingMethod는 div에 맞춰서 사이즈를 자동조절 하는 역할
			img.style.filter = "progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+src+"', sizingMethod='scale')";
		} catch (e) {
			if (!document.getElementById("ie_preview_error_" + View_area)) {
				var info = document.createElement("<p>");
				info.id = "ie_preview_error_" + View_area;
				info.innerHTML = e.name;
				preview.insertBefore(info, null);
			}
		}
  //ie가 아닐때(크롬, 사파리, FF)
	} else {
		var files = targetObj.files;
		for ( var i = 0; i < files.length; i++) {
			var file = files[i];
			var imageType = /image.*/; //이미지 파일일경우만.. 뿌려준다.
			if (!file.type.match(imageType))
				continue;
			var prevImg = document.getElementById("prev_" + View_area); //이전에 미리보기가 있다면 삭제
			if (prevImg) {
				preview.removeChild(prevImg);
			}
			var img = document.createElement("img"); 
			img.id = "prev_" + View_area;
			img.classList.add("obj");
			img.file = file;
			img.style.width = '210px'; 
			img.style.height = '240px';
			preview.appendChild(img);
			if (window.FileReader) { // FireFox, Chrome, Opera 확인.
				var reader = new FileReader();
				reader.onloadend = (function(aImg) {
					return function(e) {
						aImg.src = e.target.result;
					};
				})(img);
				reader.readAsDataURL(file);
			} else { // safari is not supported FileReader
				//alert('not supported FileReader');
				if (!document.getElementById("sfr_preview_error_"
						+ View_area)) {
					var info = document.createElement("p");
					info.id = "sfr_preview_error_" + View_area;
					info.innerHTML = "not supported FileReader";
					preview.insertBefore(info, null);
				}
			}
		}
	}
}
</script>




{% endblock %}

page/templates/merge.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<style>
    .upload {
        box-sizing: border-box;
        width: 200px;
        height: 200px;
        margin-left: 100px;
        margin-right: 50px;
        text-align: center;
        background-color: grey ;
    }
</style>

<div class="container">
    <div style="text-align: center;">
        <h1>합성 완료</h1>
    </div>
    <div class="upload" style="float: left;">
        자신의 얼굴
    </div>
    <div class="upload" style="float: left; ">
        연예인 얼굴
    </div>
    <div class="upload" style="float: left;">
        합성 완료
    </div>


    <form action="{% url 'page:merge' %}" >
        <div class="text-center" style="margin-bottom: 1%;">
            <button type="submit" class="btn btn-info">공유하기 > </button>
        </div>
    </form>
    <form action="{% url 'page:who' %}" >
        <div class="text-center" style="margin-bottom: 1%;">
            <button type="submit" class="btn btn-info">< 다시 고르기 </button>
        </div>
    </form>
</div>

iv>
            


{% endblock %}

page/templates/mix.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<div class = 'mix_one_back_ground'>
    <div class = 'subtitle'>
        <h1>Mix</h1>
    </div>
    <div class='tri'>
    </div>
    <div class = 'all'>
        <div class = 'left'>
            <div class='container'>
                <div class='single'>
                    <img src="{{ me_re }}" alt=""> 
                </div>
                <div class='single'>
                    <img src="{{ me_no }}" alt=""> 
                </div>
            </div>
            <div class='container'>
                <div class='single'>
                    <img src="{{ me_7 }}" alt=""> 
                </div>
                <div class='single'>
                    <img src="{{ me_5 }}" alt=""> 
                </div>
                <div class='single'>
                    <img src="{{ me_3 }}" alt=""> 
                </div>
            </div>
        </div>
        <div class = 'right'>
        </div>
    </div>
</div>

{% endblock %}

page/templates/mix_all.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<div class = 'mix_all_back_ground'>
    <div class = 'subtitle'>
        <h1>Mix all</h1>
    </div>
    <div class='tri'>
    </div>
    <div class = 'all'>
        <div class = 'left'>
            <div class='container'>
                <div class='single'>
                    <img src="{{ me }}" alt=""> 
                </div>
            </div>
            <div class='container'>
                <div class='single'>
                    <img src="{{ me_1 }}" alt=""> 
                </div>
                <div class='single'>
                    <img src="{{ me_2 }}" alt=""> 
                </div>
                <div class='single'>
                    <img src="{{ me_3 }}" alt=""> 
                </div>
            </div>
            <div class='container'>
                <div class='single'>
                    <img src="{{ me_no_1 }}" alt=""> 
                </div>
                <div class='single'>
                    <img src="{{ me_no_2 }}" alt=""> 
                </div>
                <div class='single'>
                    <img src="{{ me_no_3 }}" alt=""> 
                </div>
            </div>
        </div>
        <div class = 'right'>
        </div>
    </div>
</div>

{% endblock %}

page/templates/photo_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}

<div class = 'photo_list_back_ground'>
    <div class = 'subtitle'>
        <h1>Photo_list</h1>
    </div>
    <div class='tri'>
    </div>
    <div class = 'img_list'>
    {% for img in img_list %}
        <div class='single'>
            <a href="{% url 'page:mixed' img.name %}">
                <img src="{{ img.img }}">
            </a>
        </div>
    {% endfor %}
    </div>
</div>

{% endblock %}

page/templates/who.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<style>
    .upload {
        box-sizing: border-box;
        width: 200px;
        height: 200px;
        margin-left: 100px;
        margin-right: 50px;
        text-align: center;
        background-color: grey ;
    }
</style>
<div class="who_back_ground">
    <div class = 'subtitle'>
    <h1>Who?</h1>
    </div>
    <div class='tri'>
    </div>
    <div class="container d-flex flex-column mt-3" style="background-color: rgb(128,128,128,0.7); border: 5px solid grey; border-radius: 25px;">
        <br/>
        {% comment %} <div class="mb-5" style="text-align: center;">
            <h1 class="">가장 닮은 연예인은....</h1>
        </div> {% endcomment %}
        <div class="d-flex justify-content-center">
            {% for img in img_src %}
                <div class="card bg-light mx-3 mb-5" style="width: 18rem;">
                    <img src="{{ img.image }}" class="card-img-top" alt="wannabe">
                    <div class="card-body d-flex justify-content-center">
                        <a href="{% url 'page:mixed' img.name %}">
                            <button   style="margin-top: 2%;" type="submit" class="btn btn-dark">
                                <span>합성 해보기</span>
                            </button>
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class = 'button_list'>
            <div class="d-flex justify-content-center">
                <a href="{% url 'page:mixed_all' img_src.0.name img_src.1.name img_src.2.name%}">
                    <button style="margin-top: 2%; font-weight: bold;" type="submit" class="btn btn-light">
                        모든 결과 보기
                    </button>
                </a>
            </div>
            <div class="d-flex justify-content-center">
                <a href="{% url 'page:photo_list'%}">
                    <button style="margin-top: 2%; font-weight: bold;" type="submit" class="btn btn-light">
                        다른 사람과 합성
                    </button>
                </a>
            </div>
        </div>
         <br/>
    </div>
</div>

{% endblock %}